version: '3.9'

services:
  postgres:
    container_name: bast_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: bast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    container_name: bast_django
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile
    volumes:
      - ./src:/src:rw
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    environment:
      - PROCESS="DEV_DJANGO"
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
